[project]
name = "olist-data-warehouse"
version = "0.1.0"
description = "Olist analytics engineering and data warehouse project"
authors = [{ name = "ScriptFizz", email = "nsimamail@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "pandas>=2.3.3,<3.0.0",
    "numpy>=1.24.4,<2.0.0",
    "pyarrow>=12.0.1,<15.0.0",
    "pyyaml>=6.0.3,<7.0.0",
    "google-cloud-bigquery>=3.38.0,<4.0.0",
    "python-dateutil>=2.9.0.post0,<3.0.0",
    "tqdm>=4.67.1,<5.0.0",
    "faker>=38.2.0,<39.0.0",
    "python-dotenv>=1.0,<2.0",
    "typer>=0.20.0,<0.21.0",
    "kaggle>=1.8.2,<2.0.0",
    "pandera==0.18.3",
    "db-dtypes>=1.4.0,<1.5.0",
    "psycopg[binary]>=3.2,<4.0",
]

[dependency-groups]
dbt = [
    "dbt-postgres>=1.9,<2.0",
    "dbt-bigquery>=1.9,<2.0",
]

analysis = [
    "notebook>=7.5.0,<8.0.0",
    "ipykernel>=7.1.0,<8.0.0",
    "matplotlib>=3.10.8,<4.0.0",
    "seaborn>=0.13.2,<0.14.0",
    "scipy>=1.16.3,<2.0.0",
    "statsmodels>=0.14.6,<0.15.0",
    "plotly>=6.5.1,<7.0.0",
]

docs = [
    "mkdocs>=1.6.1,<2.0.0",
]

dev = [
    { include-group = "dbt" },
    "mypy>=1.19.0,<2.0.0",
    "pytest>=9.0.2,<10.0.0",
    "pre-commit>=4.5.0,<5.0.0",
    "ruff>=0.14.8,<0.15.0",
    "types-pyyaml>=6.0.12,<7.0.0",
    "pandas-stubs>=2.3.0,<3.0.0",
]

[project.scripts]
olist-extract = "olist_dw.cli.extract_csv_cli:app"
olist-transform = "olist_dw.cli.transform_cli:app"
olist-load-bigquery = "olist_dw.cli.load_bigquery_cli:app"
olist-load-layers = "olist_dw.cli.load_layers_cli:app"
olist-check-postgres = "olist_dw.cli.check_postgres_cli:app"
olist-load-postgres = "olist_dw.cli.load_postgres_cli:app"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/olist_dw"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = [
    "-ra",
    "--strict-markers",
]
markers = [
    "postgres: integration tests requiring a running PostgreSQL instance",
]