data:
  dataset_name: "olistbr/brazilian-ecommerce"

paths:
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"

bigquery:
  project_id: "olist-data-warehouse-48014"
  dataset_id: "olist_dw"
