from etl.registry.tables import TableConfig
from etl.transform.processed_schemas import (
    CustomersProcessedSchema,
    GeolocationProcessedSchema,
    OrderItemsProcessedSchema,
    OrdersProcessedSchema,
    PaymentsProcessedSchema,
    ProductsProcessedSchema,
    ReviewsProcessedSchema,
    SellersProcessedSchema,
    TranslationProcessedSchema,
)
from etl.transform.raw_schemas import (
    CustomersSchema,
    GeolocationSchema,
    OrderItemsSchema,
    OrdersSchema,
    PaymentsSchema,
    ProductsSchema,
    ReviewsSchema,
    SellersSchema,
    TranslationSchema,
)
from etl.transform.transform_data import (
    transform_customers,
    transform_geolocation,
    transform_order_items,
    transform_orders,
    transform_payments,
    transform_products,
    transform_reviews,
    transform_sellers,
    transform_translation,
)

TABLES: dict[str, TableConfig] = {
    "customers": TableConfig(
        name="customers",
        raw_filename="olist_customers_dataset.csv",
        processed_filename="customers.csv",
        raw_schema=CustomersSchema,
        processed_schema=CustomersProcessedSchema,
        transform=transform_customers,
    ),
    "orders": TableConfig(
        name="orders",
        raw_filename="olist_orders_dataset.csv",
        processed_filename="orders.csv",
        raw_schema=OrdersSchema,
        processed_schema=OrdersProcessedSchema,
        transform=transform_orders,
    ),
    "order_items": TableConfig(
        name="order_items",
        raw_filename="olist_order_items_dataset.csv",
        processed_filename="order_items.csv",
        raw_schema=OrderItemsSchema,
        processed_schema=OrderItemsProcessedSchema,
        transform=transform_order_items,
        kwargs_factory=lambda ctx: {"exchange_rate": ctx.exchange_rate},
    ),
    "payments": TableConfig(
        name="payments",
        raw_filename="olist_order_payments_dataset.csv",
        processed_filename="payments.csv",
        raw_schema=PaymentsSchema,
        processed_schema=PaymentsProcessedSchema,
        transform=transform_payments,
    ),
    "products": TableConfig(
        name="products",
        raw_filename="olist_products_dataset.csv",
        processed_filename="products.csv",
        raw_schema=ProductsSchema,
        processed_schema=ProductsProcessedSchema,
        transform=transform_products,
    ),
    "sellers": TableConfig(
        name="sellers",
        raw_filename="olist_sellers_dataset.csv",
        processed_filename="sellers.csv",
        raw_schema=SellersSchema,
        processed_schema=SellersProcessedSchema,
        transform=transform_sellers,
    ),
    "geolocation": TableConfig(
        name="geolocation",
        raw_filename="olist_geolocation_dataset.csv",
        processed_filename="geolocation.csv",
        raw_schema=GeolocationSchema,
        processed_schema=GeolocationProcessedSchema,
        transform=transform_geolocation,
    ),
    "translation": TableConfig(
        name="translation",
        raw_filename="product_category_name_translation.csv",
        processed_filename="translation.csv",
        raw_schema=TranslationSchema,
        processed_schema=TranslationProcessedSchema,
        transform=transform_translation,
    ),
    "reviews": TableConfig(
        name="reviews",
        raw_filename="olist_order_reviews_dataset.csv",
        processed_filename="reviews.csv",
        raw_schema=ReviewsSchema,
        processed_schema=ReviewsProcessedSchema,
        transform=transform_reviews,
    ),
}
