CREATE OR REPLACE TABLE `{{ PROJECT_ID }}.{{ ANALYTICS_DATASET_ID }}.snapshot_calendar` AS
SELECT
    DATE_TRUNC(d, MONTH) AS snapshot_date
FROM UNNEST(
    GENERATE_DATE_ARRAY('2016-01-01', '2018-08-31', INTERVAL 1 MONTH)
) d
GROUP BY snapshot_date;
